Notarise-gov-sg/api-notarise-healthcerts

src/common/error.ts
src/functionHandlers/notarisePdt/handler.ts
src/functionHandlers/notarisePdt/validateInputs/validateDocument.ts

Return validation errors to clients

---

src/functionHandlers/notarisePdt/handler.ts
src/models/healthCert.test.ts
src/models/healthCert.ts

**Context**
SPM notifications are only sent to NRIC holders.
**Proposed changes**
Send SPM notification to FIN holders by attempting to obtain FIN (if NRIC is not available):
```javascript
// ...
return { nricOrFin: nric?.value || fin?.value, ... }
```

Obtain FIN (if NRIC is not available) to notify recipient via SPM

---

package-lock.json
package.json

- Bump verison of @notarise-gov-sg/sns-notify-recipients to v0.0.3
- This fixes the bug where the wrong index of `testresult2` was used
- Refer to: https://github.com/Notarise-gov-sg/sns-notify-recipients/pull/3

Upgrade version of @notarise-gov-sg/sns-notify-recipients

---

serverless.yml

/CC @ryanoolala 
Providers are reporting 429 errors, they're probably maxing out the 3000 / day allowance.
This MR increases the limit for each provider to 10000 calls per day.

Increase usage limit from 3000 to 10000 per day

---

serverless.yml

add govtech apikey for staging 
to be used in conjunction with `api-notarise-healthcert-deployment`, 
e.g.
`// in api-notarise-healthcert-deployment`
```
e2e-test:
name: Start E2E test by posting data to stg api gateway
...
- run: npm ci
- run: |
curl -vX POST "${{ env.STAGING_BASE_URL }}/notarise/pdt" \
-d @./mocks/example_healthcert_with_nric_wrapped.json \
--fail --show-error \
--header "Content-Type: application/json" \
--header "x-api-key: ${{ env.X_API_KEY }}" \
env:
STAGING_BASE_URL: https://7xq2mf0b9f.execute-api.ap-southeast-1.amazonaws.com/stg
X_API_KEY: <The generated api key>
```

chore: add-govtech-apikey

---

src/common/healthCertDataValidation.ts

The `lab` entry is not necessary when endorsing PDT (ART) HealthCerts
```json
{
"resourceType": "Organization",
"name": "MacRitchie Laboratory",
"type": "Accredited Laboratory",
"contact": {
"telecom": [
{
"system": "phone",
"value": "+6562711188"
}
],
"address": {
"type": "physical",
"use": "work",
"text": "2 Thomson Avenue 4 Singapore 098888"
}
}
}
```

fix: make lab field optional to support pdt art healthcerts

---

scripts/generateInputHealthCert.ts

Was encountering this error message:
```text
Maximum call stack size exceeded
```

fix: generate wrapped cert script

---

package-lock.json
package.json
scripts/temp.ts
src/models/fhir/index.ts
src/models/fhir/parse.ts
src/models/fhir/required.ts
src/models/fhir/types.ts
test/fixtures/v2/art-unwrapped.json
test/fixtures/v2/pcr-unwrapped.json

Mappings are provided here: https://github.com/Open-Attestation/schemata/pull/38
Essentially, it should do something like:
```javascript
/* 1. FHIR parser */
parsed = fhirHelper.parse(fhirBundle as R4.IBundle);
/* 2. Required fields checker */
fhirHelper.hasRequiredFields("PCR", parsed); // throws errors[] if invalid
```
To test it, simply run:
```bash
$ npm i
$ npx ts-node scripts/temp.ts
```

179203028: FHIR Parser/Validator for PDT HealthCert Schema v2.0

---

src/services/transientStorage/index.ts

As Verify.gov.sg (https://github.com/Open-Attestation/verify.gov.sg/pull/78) is now updated to obtain the key from the anchor, the generated URLs in Notarise should follow the new format.

feat: generate urls with key in anchor

---

package-lock.json
package.json
serverless.yml
src/config.ts
src/functionHandlers/middyfy.ts
src/functionHandlers/notarisePdt/v2/handler.ts
src/middleware/withSsm.ts
src/models/euHealthCert/createEuHealthCert/createEuSignedTestQr.ts
src/models/gpayCovidCard/index.ts

- remove ssm direct load config variable from `serverless.yml`
- add `@middy/ssm` package
- add 15 mins cache ssm middleware
- load `SIGNING_EU_QR_PUBLIC_KEY`, `SIGNING_EU_QR_PRIVATE_KEY` and `GPAY_COVID_CARD_PRIVATE_KEY` variables from env using 15 mins ssm cache middleware

Chore: 180045605 remove loading public/private keys value from ssm direct

---

src/functionHandlers/notarisePdt/v2/handler.ts
src/middleware/cloudWatch.ts
src/models/fhir/constraints.ts
src/models/fhir/parse.ts
src/models/fhir/required.test.ts
src/models/fhir/required.ts
src/models/fhir/types.ts
src/models/gpayCovidCard/index.ts
src/models/healthCertV2.ts
src/models/notarizedHealthCertV2/createNotarizedHealthCert/createNotarizedHealthCert.ts
src/models/notarizedHealthCertV2/createNotarizedHealthCert/createUnwrappedHealthCert.ts

- Refactor type names in `src/models/fhir/types.ts` to have a more descriptive name (i.e. `Parsed____`)
- Introduce mappings in `src/models/fhir/constraints.ts` to convert parsed format -> original FHIR Bundle format (to aid in custom error messages)
Validate.js is now used with fully customised messaging:
```javascript
const constraints = {
"foo.bar": {
presence: {
message: `'resource.x.y[0].z' is required`,
allowEmpty: false,
},
},
"other.constraints": {
// ...
},
};
validate(parsedBundle, constraints, { fullMessages: false, format: "flat" })
```
[NEW] Improved error response:
```text
Submitted HealthCert is invalid, the following required fields in fhirBundle are missing: ["'0.Device.type.coding[0].system' is required","'0.Device.type.coding[0].code' is …
```

180023434: improve error message when validating fhir bundle

---

src/middleware/cloudWatch.ts

Right now, the casing of the type is not consistent. Thus, in cloudwatch, "PDT" is differentiated from "pdt"

chore: logging-lower-case

---

src/functionHandlers/notarisePdt/authorizedIssuers/index.ts
src/functionHandlers/notarisePdt/validateInputs/validateDocument.ts

Codebase is currently hardcoded to ONLY check against the PCR whitelist in `api-authorized-issuers`. This caused incorrect `UnrecognisedClinicError` to be thrown when a valid ART provider is attempting to endorse a valid HealthCert.
**For HealthCerts in PDT Schema v1.0**:
Continue to ONLY check against the PCR whitelist as there is no straightforward way to distinguish between PCR and ART HealthCerts. PDT Schema v1.0 is also about to be deprecated.
**For HealthCerts in PDT Schema v2.0**:
1. Check if HealthCert is single type (e.g. `"PCR"`) or multi type (e.g. `["PCR", "SER"]`).
2. If **single type**: Query respective whitelist (i.e. `whitelist.com/authorized-issuer/{domain}/{type}`)
3. If **multi type**: Hardcoded to ONLY check against PCR whitelist (since PCR and SER has the same …

180535117: check against ART whitelist

---

src/common/error.ts
src/functionHandlers/notarisePdt/validateInputs/validateDocument.ts

Log HealthCert type (e.g. `"PCR"`, `"ART"`, etc.) along with issuer domain when an `UnrecognisedClinicError` occurs

fix: improve logs for UnrecognisedClinicError

---

src/functionHandlers/notarisePdt/v1/notarisePdt.ts
src/functionHandlers/notarisePdt/v2/handler.ts
src/functionHandlers/notarisePdt/v2/notarisePdt.ts
src/services/spmNotification/index.test.ts
src/services/spmNotification/index.ts
src/services/transientStorage/index.ts

- remove multiple `directUrl` converting and change log path in transientStorage service
- refactor `spmNotification` service for v2 endpoint
- add logic for skip SPM Notification if the patient age is below 15 years
- add unit tests for `spmNotification` service

180725514 : Add logic to remove child record from SPM Notification if below 15 years old

---

src/functionHandlers/notarisePdt/v2/handler.ts
src/functionHandlers/notarisePdt/validateInputs/validateDocument.test.ts
src/functionHandlers/notarisePdt/validateInputs/validateDocument.ts
src/models/fhir/constraints.ts
src/models/fhir/index.ts
src/models/fhir/recognised.test.ts
src/models/fhir/recognised.ts
src/models/fhir/required.ts

- Refactoring variables for clarity
- Introduce `hasRecognisedFields()` for test result code validation - serves as a place to add custom FHIR validations in the future (see 16d359a678878687e98aa70a031cb5ce035e0d7a onwards)
- Enable logo size validation as well (#404)
- `260385009` (Negative): https://phinvads.cdc.gov/vads/ViewCodeSystemConcept.action?oid=2.16.840.1.113883.6.96&code=260385009
- `10828004` (Positive): https://phinvads.cdc.gov/vads/ViewCodeSystemConcept.action?oid=2.16.840.1.113883.6.96&code=10828004
- `260415000` (Not detected): https://phinvads.cdc.gov/vads/ViewCodeSystemConcept.action?oid=2.16.840.1.113883.6.96&code=260415000
- `260373001` (Detected): https://phinvads.cdc.gov/vads/ViewCodeSystemConcept.action?oid=2.16.840.1.113883.6.96&code=260373001

feat: validate test result codes

---

serverless.yml

- Remove `/notarise/pdt` and `/v1/notarise/pdt` endpoint by configuration (v1 cleanup will be done in a separate PR)
- Future paths should always have `v2` or `v_` prefix

chore: disable v1 endpoint

---

src/services/spmNotification/index.test.ts
src/services/spmNotification/index.ts

- Enable SPM healthcert notification for 'SER' or multi-type ['PCR', 'SER'] types only in staging env.

Feat: 181412318 Enable SPM notification for SER and PCR+SER

---

src/models/euDccCertificates/index.ts

- Fix issuer claim setting ([context](https://gahmen.slack.com/archives/C01Q487M2RZ/p1648121359157189?thread_ts=1647996770.708299&cid=C01Q487M2RZ))
- surprisingly https://www.npmjs.com/package/@notarise-gov-sg/eu-dcc-generator is already support for setting like this

Fix: EU DCC offline qr issuer country code

---

src/models/fhir/constraints.ts
src/models/fhir/recognised.test.ts
src/models/fhir/recognised.ts
src/models/fhir/required.test.ts
src/models/fhir/required.ts

- Refactor: Re-organise required and recognised constraints
- Validate to ensure there are 2 Observation resources for multi type HealthCerts

fix: 181751867 ensure 2 observation resources for multi type healthcert

---

serverless.yml
src/config.ts
src/models/notarizedHealthCertV2/createNotarizedHealthCert/createUnwrappedHealthCert.ts

If `process.env.REVOCATION_OCSP` is supplied, set revocation type to OCSP and specify location using the given value.

feat: set oscp responder revocation

---

src/models/fhir/constraints.ts
test/fixtures/v2/pdt_lamp_unwrapped.json
test/fixtures/v2/pdt_lamp_wrapped.json

- ACSN field is now optional for `LAMP` HealthCerts
- Create `lampGroupedFhirKeys` from `commonGroupedFhirKeys` and removing the `"observations._.observation.acsn"` property
- Update LAMP samples

chore: 182485936 make ACSN optional for LAMP HealthCerts

---

src/common/error.ts
src/functionHandlers/notarisePdt/v2/handler.ts

- return 404 error code when it is not able to find any matching records in vault data

chore: use error code 404 for mismatched vault data
